### 1. Create articleType
POST http://localhost:8080/article-type/create
Content-Type: application/json

{
  "orderNumber": 10,
  "nameUz": "Vide Yangilik",
  "nameRu": "Виде новости",
  "nameEn": "Vide News"
}

### 2. Update articleType
PUT http://localhost:8080/article-type/update/2
Content-Type: application/json

{
  "orderNumber": 2,
  "nameUz": "Muharrir tanlovi",
  "nameRu": "Выбор редактора",
  "nameEn": "Editor's Choice"
}

### 3. ArticleType page
GET http://localhost:8080/article-type/page?
    page=1&
    size=3

### 4. ArticleType delete
DELETE http://localhost:8080/article-type/delete/12

### 5. Get By Lang ArticleType
GET http://localhost:8080/article-type/lang?
    page=1&
    size=9
Accept-Language: UZ


