### 1. Profile Auth Registration Email
POST http://localhost:8080/auth/registrationEmail
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "urinovshokirjon93@gmail.com",
  "phone": "998941785150",
  "password": "12345"
}

###
###
GET http://localhost:8080/auth/verification/resendEmail/urinovshokirjon93@gmail.com

### urinovshokirjon93@gmail.com
### urinovgayratjon@gmail.com

### 2. Profile Auth Registration Sms
POST http://localhost:8080/auth/registrationSms
Content-Type: application/json

{
  "name": "Vali",
  "surname": "Valiyev",
  "email": "urinovshokirjon93@gmail.com",
  "phone": "941785150",
  "password": "12345"
}

<> 2024-05-25T105232.200.json

### 2. Profile Auth VerifySms Sms
GET http://localhost:8080/auth/verifySms?
    smsCode=Bu Eskiz dan test&
    phone=941785150

### 2. Profile login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "urinovshokirjon93@gmail.com",
  "password": "12345"
}

### 3. Profile Verification
GET http://localhost:8080/auth/verifyEmail?
    emailCade={{$random.alphanumeric(8)}}&
    email={{$random.alphanumeric(8)}}