### 1. Profile Auth Registration
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "urinovshokirjon93@gmail.com",
  "phone": "998941785150",
  "password": "12345"
}

### 2. Profile login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "urinovshokirjon93@gmail.com",
  "password": "12345"
}

### 3. Profile Verification
GET http://localhost:8080/auth/verifyEmail?
    emailCade={{$random.alphanumeric(8)}}&
    email={{$random.alphanumeric(8)}}