### 1. Category created
POST http://localhost:8080/category/adm/create
Content-Type: application/json
Authorization: Bearer

{
  "orderNumber": 5,
  "nameUz": "JAMIYAT",
  "nameRu": "ОБЩЕСТВО",
  "nameEn": "SOCIETY"
}

### 2. Update category
PUT http://localhost:8080/category/adm/update/5
Content-Type: application/json
Authorization: Bearer

{
  "orderNumber": 5,
  "nameUz": "JAMIYAT",
  "nameRu": "ОБЩЕСТВО",
  "nameEn": "SOCIETY"
}

### 3. Category list
GET http://localhost:8080/category/adm/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc0OTYyMTcsImlkIjozLCJ1c2VybmFtZSI6InVyaW5vdnNob2tpcmpvbjkzQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzE3NTgyNjE3LCJpc3MiOiJLdW5VelRlc3QifQ.-jHfMVnn-r-nWTVo-NraaTfrsD1rbyoSIV5gs_EALbDuhEFQFYxUolR0dgPx0O_n-b_8xdts_SZkWXwjJ8rRuA

### 4. Delete category
DELETE http://localhost:8080/category/adm/delete/2
Authorization: Bearer

### 5. Category By Lang
GET http://localhost:8080/category/lang
Authorization: Bearer
Accept-Language: RU
