
### 1. Create profile (ADMIN) (can create MODERATOR,PUBLISHER))
###         (name,surname,email,phone,password,status,role)
POST http://localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Aziz",
  "surname": "Azizov",
  "email": "aziz@gmail.com",
  "phone": "998941234563",
  "password": "12345"
}

### 3. Update Profile Detail (ANY) (Profile updates own details)
PUT http://localhost:8080/profile/update-own
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTY5MDkzODAsImlkIjoyLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNzE2OTk1Nzg4LCJpc3MiOiJLdW5VelRlc3QifQ.UkeU82o7UHVA581mlwCsvzAkRDuMZcPEWF1ArSe7rm9ns40u12tVP8UrP4UTfkPTrR9PSvtrA44XDwq_nbcXcQ


{
  "name": "Temur",
  "surname": "Abdurasulov",
  "email": "azizbek92@gamil.com",
  "phone": "998941521223",
  "password": "12345"
}

###  4. Profile List (ADMIN) (Pagination)
GET http://localhost:8080/profile/page?
    page=1&
    size=7

### 5. Delete Profile By Id (ADMIN)
DELETE http://localhost:8080/profile/delete/6