### 1. Region create
POST http://localhost:8080/region/create
Content-Type: application/json

{
  "orderNumber": 6,
  "nameUz": "Jizzax",
  "nameRu": "Джизак",
  "nameEn": "Jizzakh"
}


### 2. Region update
PUT http://localhost:8080/region/update/6
Content-Type: application/json

{
  "orderNumber": 6,
  "nameUz": "Jizzax",
  "nameRu": "Джизак",
  "nameEn": "Jizzakh"
}

### 3. Region list
GET http://localhost:8080/region/list

### 4. Region delete
DELETE http://localhost:8080/region/delete/1

### 5. Region By Lang
GET http://localhost:8080/region/lang
Accept-Language: UZ
